# Generated by Django 4.1 on 2022-10-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_delete_propertyforrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('rooms', models.CharField(max_length=20)),
                ('rent', models.CharField(max_length=20)),
                ('owner_no', models.CharField(max_length=20)),
            ],
        ),
    ]
