# Generated by Django 4.1 on 2022-10-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyforrent',
            name='type',
        ),
    ]
